#!/usr/bin/env php
<?php
/**
 * Reads results/*.csv (the RTT-sweep benchmark-<timestamp>.csv files and
 * cache-scope-benchmark.csv) and writes RESULTS.md at the project root as
 * markdown tables: no chart tooling, no images.
 */

$projectRoot = dirname(__DIR__);
$resultsDir = $projectRoot . '/results';

function readCsv(string $path): array
{
    $rows = [];
    $fh = fopen($path, 'r');
    $header = fgetcsv($fh);
    while (($row = fgetcsv($fh)) !== false) {
        $rows[] = array_combine($header, $row);
    }
    fclose($fh);
    return $rows;
}

function msFromNs(string|int $ns): string
{
    return number_format(((float)$ns) / 1_000_000, 3);
}

function latestBenchmarkFile(string $resultsDir): ?string
{
    $files = glob($resultsDir . '/benchmark-*.csv');
    if (!$files) {
        return null;
    }
    sort($files);
    return end($files);
}

function buildBenchmarkTables(string $file): array
{
    $rows = readCsv($file);

    $rtts = [];
    $ops = [];
    $backends = [];
    // [op][backend][rtt] = median_ns
    $medians = [];

    foreach ($rows as $row) {
        $op = $row['op'];
        $backend = $row['backend'];
        $rtt = (int)$row['rtt_ms'];

        $ops[$op] = true;
        $backends[$backend] = true;
        $rtts[$rtt] = true;
        $medians[$op][$backend][$rtt] = $row['median_ns'];
    }

    $rtts = array_keys($rtts);
    sort($rtts);
    $ops = array_keys($ops);
    $backends = array_keys($backends);
    sort($backends);

    $header = "| Operation | Backend | " . implode(' | ', array_map(fn($r) => "RTT {$r}ms", $rtts)) . " |";
    $divider = "|---|---|" . str_repeat('---|', count($rtts));

    $medianLines = [$header, $divider];
    $pageTimeLines = [$header, $divider];

    foreach ($ops as $op) {
        foreach ($backends as $backend) {
            $medianCells = [];
            $pageTimeCells = [];
            foreach ($rtts as $rtt) {
                $ns = $medians[$op][$backend][$rtt] ?? null;
                if ($ns === null) {
                    $medianCells[] = 'n/a';
                    $pageTimeCells[] = 'n/a';
                    continue;
                }
                $medianCells[] = msFromNs($ns) . ' ms';
                $pageTimeCells[] = msFromNs((int)$ns * 88) . ' ms';
            }
            $medianLines[] = "| $op | $backend | " . implode(' | ', $medianCells) . " |";
            $pageTimeLines[] = "| $op | $backend | " . implode(' | ', $pageTimeCells) . " |";
        }
    }

    return [implode("\n", $medianLines), implode("\n", $pageTimeLines)];
}

function buildCacheScopeTable(string $file): string
{
    $rows = readCsv($file);

    $lines = [
        "| Scenario | HTTP Calls | Cache Hits | Timing (ms) |",
        "|---|---|---|---|",
    ];
    foreach ($rows as $row) {
        $lines[] = "| {$row['Scenario']} | {$row['HTTP Calls']} | {$row['Cache Hits']} | {$row['Timing (ms)']} |";
    }

    return implode("\n", $lines);
}

$benchmarkFile = latestBenchmarkFile($resultsDir);
$cacheScopeFile = $resultsDir . '/cache-scope-benchmark.csv';

$sections = [];
$sections[] = "# Results";
$sections[] = "Generated by `bin/report` from `results/*.csv` on " . date('Y-m-d') . ".";

$sections[] = "## Per-op median latency by RTT";
if ($benchmarkFile === null) {
    $sections[] = "No RTT-sweep benchmark data found. Run `bin/env bench` first.";
    $sections[] = "## Reconstructed page-time (median × 88 ops/page)";
    $sections[] = "No RTT-sweep benchmark data found. Run `bin/env bench` first.";
} else {
    [$medianTable, $pageTimeTable] = buildBenchmarkTables($benchmarkFile);
    $sections[] = $medianTable;
    $sections[] = "## Reconstructed page-time (median × 88 ops/page)";
    $sections[] = $pageTimeTable;
}

$sections[] = "## Cache-scope call counts";
if (!file_exists($cacheScopeFile)) {
    $sections[] = "No cache-scope benchmark data found. Run `docker compose exec php bin/benchmark-cache-scope.php` first.";
} else {
    $sections[] = buildCacheScopeTable($cacheScopeFile);
}

$outputPath = $projectRoot . '/RESULTS.md';
file_put_contents($outputPath, implode("\n\n", $sections) . "\n");

echo "Results written to: $outputPath\n";
